version: "3.7"

services:

  trainingportal:
    image: securitylab
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
        reservations:
          cpus: "0.3"
          memory: 256M
    restart: "always" #change to always if you want the image to auto start
    build:
      context: ./trainingportal
      dockerfile: Dockerfile.trainingportal
    ports:
      - "443:443" # You could use 8080:8080 if SSL is disabled
    volumes:
       - /dojofiles
    networks:
       - portal
    environment:
       - CHALLENGE_MASTER_SALT
       - ENC_KEY
       - ENC_KEY_IV
       - DATA_DIR=/dojofiles

volumes:
  dojofiles:

networks:
  portal: