version: "3.7"

services:

  trainingportal:
    image: securecodingdojo/trainingportal
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
        reservations:
          cpus: "0.3"
          memory: 256M
    restart: "always" #change to always if you want the image to auto start
    build:
      context: ./trainingportal
      dockerfile: Dockerfile.trainingportal
    ports:
      - "8081:8081"
    volumes:
       - dojofiles
    networks:
       - portal
    environment:
       - CHALLENGE_MASTER_SALT
       - ENC_KEY
       - ENC_KEY_IV
       - DATA_DIR=/dojofiles

volumes:
  dojofiles:

networks:
  portal: